config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  # get 'auth/failure', to: redirect('/')

  get '/heartbeat', to: 'heartbeat#index'

  root to: redirect('/courses')

  get '/courses/archive', to: 'courses#archive'

  resources :courses, only: [:index, :show]

  get 'settings', to: 'settings#edit'
  post 'settings', to: 'settings#save'

  namespace :admin do
    resources :course_queues, except: [:new, :show]
    resources :course_instructors, except: [:new, :show]

    resources :courses do
      member do
        get :statistics
        get :requests
        get :groups
        post :groups
        resources :course_queues, only: [:new]
        resources :course_instructors, only: [:new] do
          get :promote, on: :collection
          post :promote, on: :collection
        end
      end
    end
  end

  resources :course_queues, only: [:show] do
    member do
      get 'outstanding_requests'
      get 'online_instructors'
      get 'instructor_message'
      get 'other_queues'
    end
  end

  mount ActionCable.server => '/cable'
end

app/models/course_instructor.rb
class CourseInstructor < ApplicationRecord
  belongs_to :course
  belongs_to :instructor, class_name: 'User'

  validate :course_instructor_already_exists

  def course_instructor_already_exists
    if course.course_instructors.find_by(instructor: instructor)
      errors.add(:instructor, "already exists for this course")
    end
  end
end

app/controllers/admin/course_instructors_controller.rb
class Admin::CourseInstructorsController < Admin::AdminController
  before_action :load_course, only: [:new, :promote]
  def new
    unless current_user.instructor_for_course?(@course)
      redirect_to root_url
    end
  end

  def promote
    # get/post map to the same action
    return render 'promote' unless request.post?

    unless params[:enrollment_code] == @course_instructor.course.enrollment_code
      # bad code
      return redirect_to root_url
    end

    unless current_user.instructor_for_course?(@course_instructor.course)
      # don't create duplicate instructors
      @course_instructor.instructor = current_user
      @course_instructor.save!
    end

    redirect_to course_url(@course_instructor.course)
  end

  def create
    @course_instructor = CourseInstructor.new
    @course_instructor.course = Course.find(params[:course_instructor][:course_id])

    unless current_user.instructor_for_course?(@course_instructor.course)
      return redirect_to root_url
    end

    @course_instructor.instructor = User.find_or_create_by({
      email: params[:instructor_email]
    })

    if @course_instructor.save
      redirect_to admin_course_url(@course_instructor.course)
    else
      render :new
    end
  end

  def destroy
    @course_instructor = CourseInstructor.find(params[:id])

    unless current_user.instructor_for_course?(@course_instructor.course)
      return redirect_to root_url
    end

    @course_instructor.destroy!

    redirect_to admin_course_url(@course_instructor.course)
  end

  private
  def load_course
    @course = Course.find_by!(slug: params[:id])
    @course_instructor = CourseInstructor.new
    @course_instructor.course = @course
  end
end

app/helpers/course_instructors_helper.rb
module CourseInstructorsHelper
end

app/views/admin/course_instructors/new.html.erb
<%= render 'shared/breadcrumbs', trail: [
    { title: @course_instructor.course.name, href: url_for(@course_instructor.course)},
    { title: 'Admin', href: admin_course_url(@course_instructor.course) },
    'Add Instructor'
] %>

<div class="six wide column">
    <h1 class="ui header">
        Add Instructor for <%= @course_instructor.course.name %>
    </h1>

    <% @course_instructor.errors.full_messages.each do |e| %>
        <div class="ui error message">
            <%= e %>
        </div>
    <% end %>

    <%= form_for [:admin, @course_instructor], html: {class: 'ui form'} do |f| %>
        <div class="field">
            <label>Email</label>
            <input type="email" name="instructor_email" placeholder="instructor@umich.edu" autofocus>
        </div>

        <%= f.hidden_field :course_id %>
        <%= f.submit 'Add', class: 'ui button' %>
    <% end %>

</div>

app/views/admin/course_instructors/promote.html.erb
<div class="six wide column">
    <h1 class="ui header">
        Self Enroll for <%= @course_instructor.course.name %>
    </h1>

    <%= form_for [:admin, @course_instructor], url: promote_admin_course_instructors_path(@course), html: {class: 'ui form'} do |f| %>
        <div class="field">
            <label>Instructor Enrollment Code</label>
            <input type="text" name="enrollment_code" autocomplete="off">
        </div>

        <%= f.hidden_field :course_id %>
        <%= f.submit 'Enroll', class: 'ui button' %>
    <% end %>

</div>