config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  # get 'auth/failure', to: redirect('/')

  get '/heartbeat', to: 'heartbeat#index'

  root to: redirect('/courses')

  get '/courses/archive', to: 'courses#archive'

  resources :courses, only: [:index, :show]

  get 'settings', to: 'settings#edit'
  post 'settings', to: 'settings#save'

  namespace :admin do
    resources :course_queues, except: [:new, :show]
    resources :course_instructors, except: [:new, :show]

    resources :courses do
      member do
        get :statistics
        get :requests
        get :groups
        post :groups
        resources :course_queues, only: [:new]
        resources :course_instructors, only: [:new] do
          get :promote, on: :collection
          post :promote, on: :collection
        end
      end
    end
  end

  resources :course_queues, only: [:show] do
    member do
      get 'outstanding_requests'
      get 'online_instructors'
      get 'instructor_message'
      get 'other_queues'
    end
  end

  mount ActionCable.server => '/cable'
end

app/controllers/admin/courses_controller.rb
class Admin::CoursesController < Admin::AdminController
  before_action :set_course, :authorize_current_user, except: [:index, :new, :create]
  before_action :authorize_global_admin, except: [:show, :edit, :update, :statistics, :groups, :requests]

  def index
    @courses = Course.all
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)

    if @course.save
      redirect_to admin_course_url(@course)
    else
      render :new
    end
  end

  def update
    if @course.update(course_params)
      redirect_to admin_course_url(@course)
    else
      render :edit
    end
  end

  def destroy
    @course.destroy!
    redirect_to admin_courses_url
  end

  def show
    @queues      = @course.course_queues.order(:name)
    @instructors = @course.course_instructors.joins(:instructor).order("users.name")
    @groups      = @course.course_groups
  end

  def statistics
    @resolved_by_day       = @course.get_resolved_by_day
    @student_contributions = @course.get_contributions(:student).first(10)
    @staff_contributions   = @course.get_contributions(:staff)
    @recent_requests       = @course.get_recently_resolved_requests
  end

  def requests
    respond_to do |format|
      format.csv {
        send_data @course.requests_to_csv,
        filename: "#{@course.slug}-requests.csv"
      }
    end
  end

  def groups
    if request.method == 'GET'
      @course_group_string = @course.get_group_string
      return
    end

    begin
      ActiveRecord::Base.transaction do
        @course.course_groups.destroy_all
        params[:groups].strip().split("\n").each do |emails_csv|
          emails = emails_csv.strip().split(',')
          next unless emails.any?

          group = @course.course_groups.create!

          emails.map do |email|
            group.students << User.find_or_create_by(email: email.strip())
          end
        end
      end
      redirect_to admin_course_url(@course)
    rescue ActiveRecord::RecordInvalid => err
      @course_group_string = params[:groups]
      @err = err
      render :groups
    end
  end

  private
  def course_params
    params.require(:course).permit(:name, :long_name, :slug, :sorting)
  end

  def set_course
    @course = Course.find_by!(slug: params[:id])
  end

  def authorize_current_user
    unless current_user.instructor_for_course?(@course)
      redirect_to root_url
    end
  end

  def authorize_global_admin
    unless current_user.global_admin?
      redirect_to root_url
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course_and_queues, except: [:index, :archive]

  def index
    @courses = Course.where(archived: false).order(:name)
  end

  def archive
    @courses = Course.where(archived: true).order(:name)
  end

  def show
  end

  private
  def set_course_and_queues
    @course = Course.find_by!(slug: params[:id])
    @queues = @course.course_queues.order(:name)
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_courses.html.erb
<div class="ui massive fluid vertical menu">
    <% @courses.each do |course| %>
        <a href="<%= url_for course %>" class="item">
            <strong><%= course.name %><%= ':' if course.long_name.present? %></strong> <%= course.long_name %>
            <% if current_user.instructor_for_course?(course) %>
                <div class="ui teal label">i</div>
            <% end %>
        </a>
    <% end %>
</div>

app/views/courses/_instructors.html.erb
<table class="ui table">
    <thead>
        <tr><th style="width: 50%">Name</th>
            <th style="width: 50%">Email</th>
            <th>
                <a href="<%= new_course_course_instructor_url(@course) %>" class="ui primary fluid labeled icon button">
                    <i class="plus icon"></i>
                    Add
                </a>
            </th>
    </tr></thead>
    <tbody>
        <% @course_instructors.each do |course_instructor| %>
            <tr>
                <td><%= course_instructor.instructor.name %></td>
                <td><%= course_instructor.instructor.email %></td>
                <td>
                    <div class="ui fluid basic buttons">
                        <%= link_to 'Delete', course_course_instructor_url(@course, course_instructor),  method: :delete, data: { confirm: 'Are you sure?' }, class: 'ui button' %>
                    </div>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/courses/_queue.html.erb
<a class="item" href="<%= url_for queue %>">
    <div class="right floated content">
        <div style="line-height: 32px;">
        <% if queue.online_instructors.empty? %>
            <span class="ui red label">Closed</span>
        <% end %>
        <% queue.online_instructors.each do |instructor| %>
            <span data-tooltip="<%= instructor.name %>" data-position="top center" data-inverted="">
                <img class="ui avatar image" src="<%= instructor.avatar_url %>">
            </span>
        <% end %>
        </div>
    </div>
    <div class="content">
        <div class="header"><%= queue.name %></div>
        <%= queue.location %>
    </div>
</a>

app/views/courses/_queues.html.erb
<table class="ui table">
    <thead>
        <tr><th style="width: 50%">Course Queue Name</th>
            <th style="width: 50%">Location</th>
            <th>
                <a href="<%= new_course_course_queue_url(@course) %>" class="ui primary labeled icon fluid button">
                    <i class="plus icon"></i>
                    New
                </a>
            </th>
    </tr></thead>
    <tbody>
        <% @course.course_queues.each do |queue| %>
            <tr>
                <td><%= queue.name %></td>
                <td><%= queue.location %></td>
                <td>
                    <div class="ui fluid basic buttons">
                        <%= link_to 'Edit', edit_course_course_queue_url(@course, queue), class: 'ui button' %>
                        <%= link_to 'Delete', course_course_queue_url(@course, queue),  method: :delete, data: { confirm: 'Are you sure?' }, class: 'ui button' %>
                    </div>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/courses/archive.html.erb
<div class="eight wide centered column">
    <h1>Archived Courses
        <a style="font-size: 12px; font-weight: normal;"
           href="/courses">view active &raquo;</a>
    </h1>
    <%= render 'courses' %>
</div>

app/views/courses/index.html.erb
<div class="eight wide centered column">
    <h1>Active Courses
        <a style="font-size: 12px; font-weight: normal;"
           href="/courses/archive">view archive &raquo;</a>
    </h1>

    <%= render 'courses' %>

    <div class="ui message">
        <p>Sign up <a href="http://eepurl.com/cHlJY5">here</a> for feature updates.</p>
    </div>
    <div class="ui message">
        <p><strong>New course?</strong> Email <a href="mailto:newcourse@eecs.help">newcourse@eecs.help</a>.</p>
    </div>

    <a class="ui large fluid button bottom padded" href="<%= url_for settings_path %>">
        Settings
    </a>

    <% if current_user.global_admin? %>
        <a class="ui large fluid primary button" href="<%= url_for admin_courses_path %>">
            Admin Panel
        </a>
    <% end %>
</div>

app/views/courses/show.html.erb
<%= render 'shared/breadcrumbs', trail: [ @course.name ] %>

<div class="eight wide centered column">
    <h1 class="ui header"> Available Queues for <%= @course.name %> </h1>

    <% if current_user.instructor_for_course? @course and Time.now < Time.new(2020, 03, 21)    %>
        <div class="ui info message">
            <div class="header">New Feature: Private Mode</div>
            <p>Enable <strong>Private Mode</strong> to hide request details from other students.</p>
            <p>Configurable in your course's <a href="<%= url_for [:admin, @course] %>">admin panel</a>.</p>
        </div>
    <% end %>
    <div class="ui fluid segment">
        <% if @queues.empty? %>
            <h4>No open queues. Try refreshing.</h4>
        <% else %>
            <div class="ui large middle aligned selection list">
                <% @queues.each do |queue| %>
                    <%= render 'queue', queue: queue %>
                <% end %>
            </div>
        <% end %>
    </div>
    <% if current_user.instructor_for_course?(@course) %>
        <a class="ui large fluid primary bottom padded button" href="<%= url_for [:admin, @course] %>">
            Admin Panel
        </a>
        <a class="ui large fluid button" href="<%= statistics_admin_course_url(@course) %>">
            Statistics
        </a>
    <% end %>
</div>