config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  # get 'auth/failure', to: redirect('/')

  get '/heartbeat', to: 'heartbeat#index'

  root to: redirect('/courses')

  get '/courses/archive', to: 'courses#archive'

  resources :courses, only: [:index, :show]

  get 'settings', to: 'settings#edit'
  post 'settings', to: 'settings#save'

  namespace :admin do
    resources :course_queues, except: [:new, :show]
    resources :course_instructors, except: [:new, :show]

    resources :courses do
      member do
        get :statistics
        get :requests
        get :groups
        post :groups
        resources :course_queues, only: [:new]
        resources :course_instructors, only: [:new] do
          get :promote, on: :collection
          post :promote, on: :collection
        end
      end
    end
  end

  resources :course_queues, only: [:show] do
    member do
      get 'outstanding_requests'
      get 'online_instructors'
      get 'instructor_message'
      get 'other_queues'
    end
  end

  mount ActionCable.server => '/cable'
end

app/controllers/admin/courses_controller.rb
class Admin::CoursesController < Admin::AdminController
  before_action :set_course, :authorize_current_user, except: [:index, :new, :create]
  before_action :authorize_global_admin, except: [:show, :edit, :update, :statistics, :groups, :requests]

  def index
    @courses = Course.all
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)

    if @course.save
      redirect_to admin_course_url(@course)
    else
      render :new
    end
  end

  def update
    if @course.update(course_params)
      redirect_to admin_course_url(@course)
    else
      render :edit
    end
  end

  def destroy
    @course.destroy!
    redirect_to admin_courses_url
  end

  def show
    @queues      = @course.course_queues.order(:name)
    @instructors = @course.course_instructors.joins(:instructor).order("users.name")
    @groups      = @course.course_groups
  end

  def statistics
    @resolved_by_day       = @course.get_resolved_by_day
    @student_contributions = @course.get_contributions(:student).first(10)
    @staff_contributions   = @course.get_contributions(:staff)
    @recent_requests       = @course.get_recently_resolved_requests
  end

  def requests
    respond_to do |format|
      format.csv {
        send_data @course.requests_to_csv,
        filename: "#{@course.slug}-requests.csv"
      }
    end
  end

  def groups
    if request.method == 'GET'
      @course_group_string = @course.get_group_string
      return
    end

    begin
      ActiveRecord::Base.transaction do
        @course.course_groups.destroy_all
        params[:groups].strip().split("\n").each do |emails_csv|
          emails = emails_csv.strip().split(',')
          next unless emails.any?

          group = @course.course_groups.create!

          emails.map do |email|
            group.students << User.find_or_create_by(email: email.strip())
          end
        end
      end
      redirect_to admin_course_url(@course)
    rescue ActiveRecord::RecordInvalid => err
      @course_group_string = params[:groups]
      @err = err
      render :groups
    end
  end

  private
  def course_params
    params.require(:course).permit(:name, :long_name, :slug, :sorting)
  end

  def set_course
    @course = Course.find_by!(slug: params[:id])
  end

  def authorize_current_user
    unless current_user.instructor_for_course?(@course)
      redirect_to root_url
    end
  end

  def authorize_global_admin
    unless current_user.global_admin?
      redirect_to root_url
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course_and_queues, except: [:index, :archive]

  def index
    @courses = Course.where(archived: false).order(:name)
  end

  def archive
    @courses = Course.where(archived: true).order(:name)
  end

  def show
  end

  private
  def set_course_and_queues
    @course = Course.find_by!(slug: params[:id])
    @queues = @course.course_queues.order(:name)
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/admin/courses/_contribution_stats.html.erb
<h3 class="ui top attached block header">
    <%= title %>
</h3>
<div class="ui bottom attached fluid segment">
    <table class="ui very basic fluid table">
        <thead>
            <tr>
                <th>User</th>
                <th>Count</th>
            </tr>
        </thead>
        <tbody>
            <% data.each do |point| %>
                <tr>
                    <td>
                        <%= point[0] %> (<%= point[1].split('@')[0] %>)<br />
                    </td>
                    <td><%= point[2] %></td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/admin/courses/_form.html.erb
<%= form_for [:admin, @course], html: {class: 'ui form'} do |f| %>
    <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>

    <div class="field">
        <%= f.label :long_name %>
        <%= f.text_field :long_name %>
    </div>

    <div class="field">
        <%= f.label :slug %>
        <%= f.text_field :slug %>
    </div>

    <div class="field">
      <%= f.label :sorting %>
       <%= f.select(:sorting, Course.sortings.keys.map {|sorting| [sorting.titleize,sorting]}) %>
    </div>

    <%= f.submit 'Submit', class: 'ui button' %>
<% end %>

app/views/admin/courses/_groups.html.erb
<% if @groups.empty? %>
    <div class="ui message">
        <strong>This course does not have any groups created.</strong>
        Import a list of groups above, and enable group mode on queues to allow
        students to share queue requests with their groupmmates and limit to
        one request per group.
    </div>
<% else %>
<pre style="width: 100%; font-family: monospace;" disabled>
<% @groups.each do |group| %>
<%= group.students.pluck(:email).join(',') %>
<% end %>
</pre>
<% end %>

app/views/admin/courses/_instructors.html.erb
<table class="ui table">
    <thead>
        <tr><th style="width: 50%">Name</th>
            <th style="width: 50%">Email</th>
            <th>
                <a href="<%= new_admin_course_instructor_url(@course) %>" class="ui primary fluid labeled icon button">
                    <i class="plus icon"></i>
                    Add
                </a>
            </th>
    </tr></thead>
    <tbody>
        <% instructors.each do |course_instructor| %>
            <tr>
                <td><%= course_instructor.instructor.name %></td>
                <td><%= course_instructor.instructor.email %></td>
                <td>
                    <div class="ui fluid basic buttons">
                        <%= link_to 'Delete', admin_course_instructor_path(course_instructor),  method: :delete, data: { confirm: 'Are you sure?' }, class: 'ui button' %>
                    </div>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/admin/courses/_queues.html.erb
<table class="ui table">
    <thead>
        <tr><th style="width: 50%">Course Queue Name</th>
            <th style="width: 40%">Location</th>
            <th style="width: 10%">Group Mode</th>
            <th style="width: 10%">Exclusive Mode</th>
            <th style="width: 10%">Private Mode</th>
            <th style="width: 10%">Jitter</th>
            <th>
                <a href="<%= new_admin_course_queue_path(@course) %>" class="ui primary labeled icon fluid button">
                    <i class="plus icon"></i>
                    New
                </a>
            </th>
    </tr></thead>
    <tbody>
        <% @course.course_queues.each do |queue| %>
            <tr>
                <td><%= queue.name %></td>
                <td><%= queue.location %></td>
                <td><div class="ui disabled toggle checkbox">
                        <input type="checkbox" disabled="disabled" <%= 'checked' if queue.group_mode %>>
                        <label></label>
                    </div></td>
                <td><div class="ui disabled toggle checkbox">
                        <input type="checkbox" disabled="disabled" <%= 'checked' if queue.exclusive %>>
                        <label></label>
                    </div></td>
                <td><div class="ui disabled toggle checkbox">
                        <input type="checkbox" disabled="disabled" <%= 'checked' if queue.hide_details_from_students %>>
                        <label></label>
                    </div></td>
                <td><div class="ui disabled toggle checkbox">
                        <input type="checkbox" disabled="disabled" <%= 'checked' if queue.add_requested_at_jitter %>>
                        <label></label>
                    </div></td>
                <td>
                    <div class="ui fluid basic buttons">
                        <%= link_to 'Edit', edit_admin_course_queue_path(queue), class: 'ui button' %>
                        <%= link_to 'Delete', admin_course_queue_path(queue),  method: :delete, data: { confirm: 'Are you sure?' }, class: 'ui button' %>
                    </div>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/admin/courses/_recent_request_stats.html.erb
<h3 class="ui top attached block header">
    Recent Requests
</h3>
<div class="ui attached fluid segment">
    <table class="ui very basic fluid table">
        <thead>
            <tr>
                <th>Requester</th>
                <th>Queue</th>
                <th>Request Details</th>
                <th>Resolver Details</th>
            </tr>
        </thead>
        <tbody>
            <% requests.each do |request| %>
                <tr>
                    <td> <%= request.requester.name %> (<%= request.requester.email.split('@')[0] %>)<br /> at <%= request.created_at.in_time_zone("Eastern Time (US & Canada)").strftime("%r %b %d %Y %Z") %></td>
                <td><%= request.course_queue.name %></td>
                <td>
                    <strong>Location:</strong> <%= request.location.present? ? request.location : "N/A" %><br />
                    <strong>Description:</strong> <%= request.description.present? ? request.description : "N/A" %>
            </td>
            <td>
                <%= request.resolver.name %> (<%= request.resolver.email.split('@')[0] %>)<br /> at <%= request.resolved_at.in_time_zone("Eastern Time (US & Canada)").strftime("%r %b %d %Y %Z") %>
        </td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>
<div class="ui small bottom attached fluid segment">
    <a href="<%= requests_admin_course_url(@course, format: :csv) %>">All Requests [csv]</a>
</div>

app/views/admin/courses/_self_enroll.html.erb
<% uri = promote_admin_course_instructors_url(@course) %>

<div class="ui message">
    <div class="content">
        Instructors may self-enroll with code <strong><code><%= code %></code></strong> at
        <a href="<%= uri %>"><%= uri %></a>.
    </div>
</div>

app/views/admin/courses/_sort.html.erb
<% if @course.sort_by_number_of_resolved_requests_this_session? %>
number of previous resolved requests
<% else %>
time request is created
<% end %>

app/views/admin/courses/edit.html.erb
<%= render 'shared/breadcrumbs', trail: [
    { title: 'Admin', href: admin_courses_path},
    "Edit #{@course.name}",
] %>

<div class="six wide column">
    <h1 class="ui header">
        Edit <%= @course.name %>
    </h1>

    <%= render 'form' %>
</div>

app/views/admin/courses/groups.html.erb
<%= render 'shared/breadcrumbs', trail: [
    { title: @course.name, href: url_for(@course)},
    'Groups'
] %>

<div class="sixteen wide column">
    <h1 class="ui header">
        <%= @course.name %> Course Groups
        <a href="https://github.com/mterwill/office-hours-help-queue/wiki/Group-mode">
            <i class="ui help circle grey small icon"></i>
        </a>
    </h1>
</div>

<div class="eight wide column">
    <% if @err.present? %>
        <div class="ui error message">
            <%= @err %>
        </div>
    <% end %>

    <p>Upload a comma-separated list of emails. One group per line. e.g.</p>
    <pre>
bob@umich.edu,mary@umich.edu,sue@umich.edu
josh@umich.edu,matt@umich.edu,anna@umich.edu</pre>
    <p>Would create two groups: [Bob, Mary, Sue] and [Josh, Matt, Anna].</p>
    <%= form_tag(nil, {class: 'ui form'}) do %>
        <div class="field">
            <textarea name="groups"
             style="font-family: monospace;"
             placeholder="user1@umich.edu,user2@umich.edu,user3@umich.edu"
             ><%= h(@course_group_string) %></textarea>
        </div>
        <div class="field">
            <button type="submit" class="ui button">Upload</div>
        </div>
    <% end %>
</div>

app/views/admin/courses/index.html.erb
<%= render 'shared/breadcrumbs', trail: [
    'Admin'
] %>

<div class="ten wide column">
    <h1 class="ui header">
        All Courses
    </h1>

    <table class="ui table">
        <thead>
            <tr><th style="width: 80%">Course Name</th>
                <th>
                    <a href="<%= new_admin_course_path %>" class="ui primary labeled icon fluid button">
                        <i class="plus icon"></i>
                        New
                    </a>
                </th>
            </tr></thead>
            <tbody>
                <% @courses.each do |course| %>
                    <tr>
                        <td><%= course.name %></td>
                        <td>
                            <div class="ui fluid basic buttons">
                                <%= link_to 'Edit', edit_admin_course_path(course), class: 'ui button' %>
                                <%= link_to 'Delete', admin_course_path(course),  method: :delete, data: { confirm: 'Are you sure?' }, class: 'ui button' %>
                            </div>
                        </td>
                    </tr>
                <% end %>
            </tbody>
    </table>
</div>

app/views/admin/courses/new.html.erb
<%= render 'shared/breadcrumbs', trail: [
    { title: 'Admin', href: admin_courses_path},
    'New Course',
] %>

<div class="six wide column">
    <h1 class="ui header">
        New Course
    </h1>

    <%= render 'form' %>
</div>

app/views/admin/courses/show.html.erb
<%= render 'shared/breadcrumbs', trail: [
    { title: @course.name, href: url_for(@course)},
    'Admin'
] %>

<div class="twelve wide column">
    <h1 class="ui header">
        <%= @course.name %>
        Course Administration
    </h1>

    <a href="<%= edit_admin_course_url(@course) %>" class="ui button">
        Edit Course Details
    </a>

    <h2>Course Queues</h2>
    <%= render 'queues', queues: @queues %>

    <h2>Course Groups
        <a href="https://github.com/mterwill/office-hours-help-queue/wiki/Group-mode">
            <i class="ui help circle small grey icon"></i>
        </a>
        <a class="ui labeled icon right floated primary button" href="<%= groups_admin_course_url(@course) %>">
            <i class="plus icon"></i>
        Import</a>
    </h2>
    <%= render 'groups', groups: @groups %>

    <h2>Course Instructors</h2>
    <%= render 'self_enroll', code: @course.enrollment_code %>
    <%= render 'instructors', instructors: @instructors %>
</div>

app/views/admin/courses/statistics.html.erb
<%= render 'shared/breadcrumbs', trail: [
    { title: @course.name, href: url_for(@course)},
    'Statistics'
] %>

<div class="sixteen wide column">
    <h1 class="ui header">
        <%= @course.name %>
        Statistics

        <div class="ui horizontal teal label">
            Instructor Only
        </div>
    </h1>
</div>

<div class="ten wide column">
    <canvas id="resolved-by-day" style="width: 100%; height: 250px;"></canvas>
</div>
<div class="six wide column">
    <canvas id="staff-contributions" style="height: 198px;"></canvas>
</div>


<div class="sixteen wide column">
    <%= render 'contribution_stats', title: "Student Contributions (top 10)", data: @student_contributions %>
</div>

<div class="sixteen wide column">
    <%= render 'recent_request_stats', requests: @recent_requests %>
</div>

<%= javascript_include_tag "Chart.min" %>
<%= javascript_include_tag "randomColor" %>
<%= javascript_include_tag "statistics" %>